import Head from 'next/head'
import '../styles/globals.css'
import Footer from '../Components/Footer'
// import Navbar from '../Components/Navbar'
import dynamic from 'next/dynamic'
const Navbar = dynamic(() => import('../Components/Navbar'), { ssr: false })
function MyApp({ Component, pageProps }) {
  return<>
    <Head>
        <title>Keeper App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
  <Component {...pageProps} />
  <Footer/>
  </> 
}

export default MyApp
